cw18_1/Models/ErrorViewModel.cs
namespace cw18_1.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

cw18_1/Controllers/ButtonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AppCore.DTO;
using AppService;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace cw18_1.Controllers
{
    public class ButtonController : Controller
    {
        //private readonly IButtonService _service;
        //public ButtonController(ButtonService service)
        //{
        //    _service = service;
        //}
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        //public IActionResult ProvinceMemberList()
        //{
        //    List<ProvinceMemberList> Member = _service.ProvinceMemberList();
        //    return View(Member);
        //}
    }
}

cw18_1/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using cw18_1.Models;
using AppService;
using AppCore.DTO;

namespace cw18_1.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
   

    //public HomeController(ILogger<HomeController> logger)
    //{
    //    _logger = logger;
     
    //}

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

}

cw18_1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
   
</div>

cw18_1/Views/Home/ProvinceMemberList.cshtml
@model List<ProvinceMemberList>

<table>
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                ProvinceName
            </th>
            <th>
                Members
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(ProvinceMemberList member in Model)
{
                <tr>
                    <td>
                        @member.Id
                    </td>
                    <td>
                        @member.Name
                    </td>
                    <table>
                        <tbody>
                            @foreach(string fullName in member.listMemberName )
{
                                    <td>@fullName</td>
}
                        </tbody>
                    </table>
                </tr>
}
    </tbody>
</table>

cw18_1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - cw18_1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/cw18_1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">cw18_1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-area="" asp-controller="Button" asp-action="ProvinceMemberList">نمایش اعضای کتابخانه به تفکیک استان</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 1402 - cw18_1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>